FROM ubuntu:16.04

MAINTAINER Frojd
LABEL version="v1.0.0"

RUN apt-get update \
    && apt-get -y install supervisor nginx ssh openssh-server \
    && apt-get -y install rsync wget vim curl net-tools locales

COPY docker/files/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY docker/files/nginx.conf /etc/nginx/sites-enabled/default
COPY docker/files/deploy_rsa.pub /root/.ssh/authorized_keys

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

CMD service ssh start && supervisord
