version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: elixir:1.5.1
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: ubuntu
    steps:
      - checkout
      - run:
          command: |
            cd src
            mix local.hex --force
            mix local.rebar
            mix deps.get
            mix ecto.create
            mix test

