---
- name: Deploy phoenix application
  hosts: all

  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/../src/_build"
    ansistrano_keep_releases: 3
    ansistrano_deploy_via: rsync
    ansistrano_after_update_code_tasks_file: "tasks/after-update-code.yml"
    ansistrano_after_symlink_tasks_file: "tasks/after-symlink.yml"
    app_name: example_app
    mix_env: prod
    app_port: 8080
    ansistrano_allow_anonymous_stats: no
  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }

