use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# ExampleAppWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :example_app, ExampleAppWeb.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: "${HOST}", port: {:system, "PORT"}],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  root: ".",
  ssl: false,
  code_reloader: false

# Do not print debug messages in production
config :logger, level: :info

config :phoenix_environment_settings, ExampleAppWeb.Endpoint,
  secret_key_base: "${SECRET_KEY_BASE}"

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :example_app, ExampleAppWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [:inet6,
#               port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :example_app, ExampleAppWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :example_app, ExampleAppWeb.Endpoint, server: true
#
#
config :phoenix, :serve_endpoints, true

# Configure your database
config :example_app, ExampleApp.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "${DATABASE_USER}",
  password: "${DATABASE_PASSWORD}",
  database: "${DATABASE_NAME}",
  hostname: "${DATABASE_HOST}",
  pool_size: 10

# Finally import the config/prod.secret.exs
# which should be versioned separately.
try do
  import_config "prod.secret.exs"
rescue
  e in Mix.Config.LoadError ->
    case e do
      %Mix.Config.LoadError{error: %File.Error{}} ->
        :ok
      _ ->
        reraise(e, System.stacktrace)
    end
end
